FROM node:20-alpine
WORKDIR /app

# Copy package files
COPY package*.json ./
COPY packages/api/package*.json ./packages/api/
COPY packages/shared/package*.json ./packages/shared/

# Install dependencies
RUN npm ci --production

# Copy source code
COPY packages/shared ./packages/shared
COPY packages/api ./packages/api

# Set working directory
WORKDIR /app/packages/api

EXPOSE 3000
CMD ["node", "dist/index.js"]
